### ISSUE TITLE
Does this work with FlatList?

### ISSUE THREAD

**Issue by duro** [NadiKuts/react-native-pull-refresh#9]
I know FlatList has built in pull-to-refresh functionality, but I have yet to find a way to override it with something other than the default. Since FlatList is based on `ScrollView` should it work?

**Comment by duro** [comment]
The short answer is... yes, it does.

**Comment by rafalzawadzki** [comment]
@ajaykumar97 have you found a solution? I have exactly the same problem.

**Comment by ajaykumar97** [comment]
@rafalzawadzki No. Actually I have build my own Pull-To-Refresh component for android.
